# Generated by Django 5.2.7 on 2025-10-31 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of the study material"
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("notes", "Study Notes"),
                            ("practice", "Practice Questions"),
                            ("syllabus", "Syllabus"),
                            ("previous", "Previous Year Questions"),
                            ("guide", "Study Guide"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload PDF, DOC, or DOCX files",
                        upload_to="study_materials/%Y/%m/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Only published materials are visible to users",
                    ),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_materials",
                        to="content.category",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Material",
                "verbose_name_plural": "Study Materials",
                "ordering": ["-created_at"],
            },
        ),
    ]
